# Generated by Django 5.2.1 on 2025-06-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Roll_No', models.CharField(max_length=20, unique=True)),
                ('Student_Email', models.EmailField(max_length=100, unique=True)),
                ('Student_Course', models.CharField(max_length=100)),
            ],
        ),
    ]
