# Generated by Django 5.2.1 on 2025-06-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Email', models.EmailField(max_length=100, unique=True)),
                ('Teacher_Department', models.CharField(max_length=100)),
                ('Teacher_Experience', models.IntegerField()),
            ],
        ),
    ]
