# Generated by Django 5.2.2 on 2025-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=200)),
                ('User_Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
