# Generated by Django 5.2.3 on 2025-06-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RecipeTitle", models.CharField(max_length=100)),
                ("RecipeDesciption", models.TextField(max_length=500)),
                ("RecipeIngredients", models.CharField(max_length=100)),
                ("RecipeInstrauction", models.CharField(max_length=100)),
                ("RecipeImage", models.ImageField(upload_to="Media/recipe")),
            ],
        ),
    ]
