# Generated by Django 5.2.1 on 2025-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('StudentAddress', models.TextField(max_length=200)),
                ('StudentDepartment', models.CharField(max_length=100)),
                ('StudentAge', models.IntegerField()),
            ],
        ),
    ]
