# Generated by Django 5.2.3 on 2025-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfomodel",
            name="Profile",
            field=models.ImageField(upload_to="Media/pic"),
        ),
    ]
